<?php

/**
 * @file
 * Views Sexy Throbber main module file.
 */

/**
 * Implements hook_menu().
 */
function views_sexy_throbber_menu() {
  $items = array();
  $items['admin/structure/views/settings/trobber'] = array(
    'title' => 'Views Sexy Throbber',
    'description' => 'Configure the Views sexy throbber.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('views_sexy_throbber_settings'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'settings_form.inc',
    'weight' => 10,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function views_sexy_throbber_init() {

  // Add the css file to your site DOM.
  drupal_add_css('public://views_sexy_throbber/views_sexy_throbber.css');
}

/**
 * Implements hook_css3pie().
 */
function views_sexy_throbber_css3pie() {

  // Add support for the "CSS3PIE" module to deliver IE comapability.
  return array(
    'views_sexy_throbber' => array(
      'div.view div.ajax-progress',
      'div.view div.throbber',
      'div.ajax-progress',
      'div.throbber',
    ),
  );
}
