<?php

/**
 * Implements hook_node_view().
 */
function livenewsads_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'article') {
    $citylumber = 0;
    drupal_add_css(drupal_get_path('module', 'livenewsads') . '/css/livenewsads.css');
    $t = 'all';
    $matched_content = '';
    if (isset($node->field_category[LANGUAGE_NONE]) && !empty($node->field_category[LANGUAGE_NONE])) {
      foreach ($node->field_category[LANGUAGE_NONE] as $k => $v) {
        switch ($v['tid']) {
          case '16':
            $t = 'sanangelo';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content San Angelo -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="3510528859"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '17':
            $t = 'texas';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Texas -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="6463995259"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '18':
            $t = 'national';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content National -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="7801127659"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '19':
            $t = 'international';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content International -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="1754594059"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '22':
            $t = 'livethought';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Opinion -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="9138260051"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '25':
            $t = 'business';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Business -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="7521926057"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '26':
            $t = 'politics';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Politics -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="5905592056"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '27':
            $t = 'county';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content County -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="8859058450"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;
          case '30':
            $t = 'sports';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Sports -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="2952125650"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '31':
            $t = 'crime';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Crime Stories -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="8219930056"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '42':
            $t = 'rodeo';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Rodeo -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="2812524852"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '44':
            $t = 'crashes';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Car Crashes -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="9836264056"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '51':
            $t = 'health';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Health Care -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="8080329257"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case '52':
            $t = 'education';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Education Stories -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="5126862853"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
          case 63:
            $citylumber = 1;
            break;
          default:
            $t = 'all';
            $matched_content = <<<EOT
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Matched Content Default -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0297859658733160"
     data-ad-slot="7242724450"
     data-ad-format="autorelaxed"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOT;

            break;
        }
      }
      $aol = <<<EOT
<!-- TAG START { player: "19538-835306-Hyde Outstream Mobile", owner: "ONE Video by AOL", for: "ONE Video by AOL" - BEINJS } -->
<div id="57e44c7ee3bb5672f8a3f5f8" class="vdb_player vdb_mobile vdb_57e44c7ee3bb5672f8a3f5f856bcd17ce4b018167fea5539">
  <script type="text/javascript" src="//delivery.vidible.tv/jsonp/pid=57e44c7ee3bb5672f8a3f5f8/56bcd17ce4b018167fea5539_bein.js"></script>
</div>
<!-- TAG END { date: 09/22/16 } -->
<!-- TAG START { player: "19538-835303-Hyde Outstream Desktop", owner: "ONE Video by AOL", for: "ONE Video by AOL" - BEINJS } -->
<div id="57e44c51e3bb5672f8a3f5e9" class="vdb_player vdb_desktop vdb_57e44c51e3bb5672f8a3f5e956bcd17ce4b018167fea5539">
  <script type="text/javascript" src="//delivery.vidible.tv/jsonp/pid=57e44c51e3bb5672f8a3f5e9/56bcd17ce4b018167fea5539_bein.js">
</script></div><!-- TAG END { date: 09/22/16 } -->
EOT;
$js_aol = <<<EOT
(function ($) {
  console.log(isMobile());
  if (isMobile() == false) {
    // Remove Mobile version
    $('#57e44c7ee3bb5672f8a3f5f8').remove();
  }
  else {
    // Remove the Desktop version
    $('#57e44c51e3bb5672f8a3f5e9').remove();
  }
}(jQuery));
function isMobile() {
  try{ document.createEvent("TouchEvent"); return true; }
  catch(e){ return false; }
}     

EOT;

      // Place ads into the story body:
      if (isset($node->content['body'][0]['#markup']) && strlen($node->content['body'][0]['#markup']) > 550 && $citylumber == 0) {

        $dom = new simple_html_dom();
        $dom->load($node->content['body'][0]['#markup']);
        // Determine the number of ads
        $paras = [];
        foreach ($dom->find("p") as $element) {
          $paras[] = $element->outertext;
        }
        $ad_count = ceil((int) count($paras) / 4);
        $adspot = [];
        for ($x = 1; $x <= $ad_count; $x++) {
          if ($node->nid == '16407') {
            $block = block_load('dfp', 'newsbody_football_' . $x);
            $adspot[$x] = drupal_render(_block_get_renderable_array(_block_render_blocks([$block])));
          }
          else {
            $block = block_load('dfp', 'newsbody_' . $x);
            $adspot[$x] = drupal_render(_block_get_renderable_array(_block_render_blocks([$block])));
          }
        }
        $string = substr($node->content['body'][0]['#markup'], 0, strpos($node->content['body'][0]['#markup'], "</p>") + 4);
        // Add the banner ad code
        $banner_added = $string . $adspot[1];
        // Add the first banner the old fashioned way
        $node->content['body'][0]['#markup'] = str_replace($string, $banner_added, $node->content['body'][0]['#markup']);
        $show_ads = 1;
        if (isset($node->field_insert_ads[LANGUAGE_NONE][0]['value'])) {
          if ($node->field_insert_ads[LANGUAGE_NONE][0]['value'] == 1) {
            $show_ads = 0;
          }
        }
        if ($show_ads == 1) {
          // Above, we placed the first ad, so start with ad #2. The array() starts at 1.
          drupal_add_js($js_aol, array('type' => 'inline', 'scope' => 'header', 'weight' => 0));
          $i = 2;
          $aolinserted = 0;
          for ($x = 4; $x <= count($paras); $x++) {
            if ($x % 4 == 0) {
              $string = $paras[$x];
              if ($aolinserted == 0) {
                $banner_added = $aol . $string;
                //$i = 2;
                $aolinserted = 1;
              }
              else {
                $banner_added = $adspot[$i] . $string;
              }
              //$happy = str_replace($string, $banner_added, $node->content['body'][0]['#markup']);
              $node->content['body'][0]['#markup'] = str_replace($string, $banner_added, $node->content['body'][0]['#markup']);
              $i++;
            }
          }
        }
      }
      $copyright = '<div class="copyright"> &copy; ' . date('Y') . ' Copyright Hyde Interactive, Inc. All rights reserved. This material may not be published, broadcast, rewritten, or redistributed.</div>';
      if ($node->nid == '16407') {
        $ad = block_load('dfp', 'article_bottom_football');
      }
      else {
        $ad = block_load('dfp', 'article_bottom_' . $t);
      }
      $node->content['body'][0]['#markup'] .= drupal_render(_block_get_renderable_array(_block_render_blocks([$ad]))) . $copyright;
      // Add the "Recommended for You" block of stories:
      //$thumbs = views_embed_view('news_thumbs', 'block');
      //$node->content['body'][0]['#markup'] .= '<div id="block-views-news-thumbs-block" class="clearfix"><h2>Recommended for You</h2>' . $thumbs . '</div>';
    }
    // Google Surveys
    $js = <<<EOT
(function() {
  var ARTICLE_URL = window.location.href;
  var CONTENT_ID = 'everything';
  document.write(
    '<scr'+'ipt '+
    'src="//survey.g.doubleclick.net/survey?site=_svfs4ntpfivgotmieqafjocpeu'+
    '&amp;url='+encodeURIComponent(ARTICLE_URL)+
    (CONTENT_ID ? '&amp;cid='+encodeURIComponent(CONTENT_ID) : '')+
    '&amp;random='+(new Date).getTime()+
    '" type="text/javascript">'+'\x3C/scr'+'ipt>');
})();
EOT;
    drupal_add_js($js, [
      'type' => 'inline',
      'scope' => 'header',
      'weight' => -1,
    ]);
    $js = <<<EOT
try { _402_Show(); } catch(e) {}
EOT;

    $prefix = '<div class="p402_premium">';
    $suffix = "</div><script type=\"text/javascript\">\n" . $js . "\n" . "</script>";
    $node->content['body'][0]['#markup'] = $prefix . $node->content['body'][0]['#markup'] . $suffix;
    $thumbs = views_embed_view('news_thumbs', 'block');
    $node->content['body'][0]['#markup'] .= '<div id="block-views-news-thumbs-block" class="clearfix"><h2>Recommended for You</h2>' . $thumbs . '</div>';
  }
  if ($view_mode == 'teaser') {
    if ($node->type == 'venue') {
      $ad = block_load('dfp', 'article_bottom_event');
      $node->content['field_map'][0]['#markup'] .= drupal_render(_block_get_renderable_array(_block_render_blocks([$ad])));
    }
  }

}

