<?php

/**
 * Implements hook_node_view().
 */
function livenewsads_node_view($node, $view_mode, $langcode) {
	$adspot1 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-101\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-101\');</script></div>';
	$adspot2 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-102\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-102\');</script></div>';
	$adspot3 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-103\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-103\');</script></div>';
	$adspot4 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-104\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-104\');</script></div>';
	$adspot5 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-105\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-105\');</script></div>';
	$adspot6 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-106\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-106\');</script></div>';
	$adspot7 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-107\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-107\');</script></div>';
	$adspot8 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-108\' class=\'newsbodyplacement ads\><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-108\');</script></div>';
	$adspot9 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-109\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-109\');</script></div>';
	$adspot10 = '<!-- SALive_B_News --><div id=\'div-gpt-ad-1425500431462-110\' class=\'newsbodyplacement ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-110\');</script></div>';
	$t = '';
  if ($view_mode == 'full' && $node->type == 'article') {
	  drupal_add_css(drupal_get_path('module', 'livenewsads') .  '/css/livenewsads.css');
    if (isset($node->field_category[LANGUAGE_NONE]) && !empty($node->field_category[LANGUAGE_NONE])) {
      foreach($node->field_category[LANGUAGE_NONE] as $k => $v) {
        if (empty($t)) {
          if ($v['tid'] == '31') {
            $t = 'crime';
          }
          if ($v['tid'] == '44') {
            $t = 'crashes';
          }
          if ($v['tid'] == '51') {
            $t = 'health';
          }
        }
      }
    }
    $two = $three = $four = FALSE;
    if (strlen($node->content['body'][0]['#markup']) > 550) {
      $two = FALSE;
      $dom = new simple_html_dom();
      $dom->load($node->content['body'][0]['#markup']);
      // Count paragraphs
      $paras = $dom->find("p");
      if (count($paras) > 7) {
        $two = TRUE;
      }
      if (count($paras) > 12) {
        $three = TRUE;
      }
      if (count($paras) > 17) {
        $four = TRUE;
      }
      if (count($paras) > 22) {
        $five = TRUE;
      }
      if (count($paras) > 27) {
        $six = TRUE;
      }
      if (count($paras) > 32) {
        $seven = TRUE;
      }
      if (count($paras) > 37) {
        $eight = TRUE;
      }
      if (count($paras) > 42) {
        $nine = TRUE;
      }
      if (count($paras) > 47) {
        $ten = TRUE;
      }
      if (count($paras) > 52) {
        $eleven = TRUE;
      }
      if (count($paras) > 57) {
        $twelve = TRUE;
      }
      if (count($paras) > 62) {
        $therteen = TRUE;
      }
      if (count($paras) > 67) {
        $fourteen = TRUE;
      }
      if (count($paras) > 72) {
        $fifteen = TRUE;
      }
      if (count($paras) > 77) {
        $sexteen = TRUE;
      }
      if (count($paras) > 82) {
        $seventeen = TRUE;
      }
      $string = substr($node->content['body'][0]['#markup'], 0, strpos($node->content['body'][0]['#markup'], "</p>")+4);
      // add the banner ad code
      $banner_added = $string . $adspot1;
      // add the first banner the old fashioned way
      $node->content['body'][0]['#markup'] = str_replace($string, $banner_added, $node->content['body'][0]['#markup']);
			$show_ads = 1;
			if (isset($node->field_insert_ads[LANGUAGE_NONE][0]['value'])) {
			  if ($node->field_insert_ads[LANGUAGE_NONE][0]['value'] == 1) {
				  $show_ads = 0;
				}
			}
			if ($show_ads == 1) {
				if ($two) {
					$string2 = $paras[5];
					$banner_added2 =  $adspot2 . $string2;
					$node->content['body'][0]['#markup'] = str_replace($string2, $banner_added2, $node->content['body'][0]['#markup']);
				}
				if ($three) {
					$string3 = $paras[10];
					$banner_added3 =  $adspot3 . $string3;
					$node->content['body'][0]['#markup'] = str_replace($string3, $banner_added3, $node->content['body'][0]['#markup']);
				}
				if ($four) {
					$string4 = $paras[15];
					$banner_added4 =  $adspot4 . $string4;
					$node->content['body'][0]['#markup'] = str_replace($string4, $banner_added4, $node->content['body'][0]['#markup']);
				}
				if ($five) {
					$string5 = $paras[20];
					$banner_added5 =  $adspot5 . $string5;
					$node->content['body'][0]['#markup'] = str_replace($string5, $banner_added5, $node->content['body'][0]['#markup']);
				}
				if ($six) {
					$string6 = $paras[25];
					$banner_added6 =  $adspot6 . $string6;
					$node->content['body'][0]['#markup'] = str_replace($string6, $banner_added6, $node->content['body'][0]['#markup']);
				}
				if ($seven) {
					$string7 = $paras[30];
					$banner_added7 =  $adspot7 . $string7;
					$node->content['body'][0]['#markup'] = str_replace($string7, $banner_added7, $node->content['body'][0]['#markup']);
				}
				if ($eight) {
					$string8 = $paras[35];
					$banner_added8 =  $adspot8 . $string8;
					$node->content['body'][0]['#markup'] = str_replace($string8, $banner_added8, $node->content['body'][0]['#markup']);
				}
				if ($nine) {
					$string9 = $paras[40];
					$banner_added9 =  $adspot9 . $string9;
					$node->content['body'][0]['#markup'] = str_replace($string9, $banner_added9, $node->content['body'][0]['#markup']);
				}
				if ($ten) {
					$string10 = $paras[45];
					$banner_added10 =  $adspot10 . $string10;
					$node->content['body'][0]['#markup'] = str_replace($string10, $banner_added10, $node->content['body'][0]['#markup']);
				}
				if ($eleven) {
					$string11 = $paras[50];
					$banner_added11 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string11;
					$node->content['body'][0]['#markup'] = str_replace($string11, $banner_added11, $node->content['body'][0]['#markup']);
				}
				if ($twelve) {
					$string12 = $paras[55];
					$banner_added12 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string12;
					$node->content['body'][0]['#markup'] = str_replace($string12, $banner_added12, $node->content['body'][0]['#markup']);
				}
				if ($therteen) {
					$string13 = $paras[60];
					$banner_added13 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string13;
					$node->content['body'][0]['#markup'] = str_replace($string13, $banner_added13, $node->content['body'][0]['#markup']);
				}
				if ($fourteen) {
					$string14 = $paras[65];
					$banner_added14 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string14;
					$node->content['body'][0]['#markup'] = str_replace($string14, $banner_added14, $node->content['body'][0]['#markup']);
				}
				if ($fifteen) {
					$string15 = $paras[70];
					$banner_added15 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string15;
					$node->content['body'][0]['#markup'] = str_replace($string15, $banner_added15, $node->content['body'][0]['#markup']);
				}
				if ($sixteen) {
					$string16 = $paras[75];
					$banner_added16 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string16;
					$node->content['body'][0]['#markup'] = str_replace($string16, $banner_added16, $node->content['body'][0]['#markup']);
				}
				if (isset($seventeen) && $seventeen == TRUE) {
					$string17 = $paras[80];
					$banner_added17 =  '<div class="newsbodyplacement ads"><script type="text/javascript">broadstreet.zone(40349);</script></div>' . $string17;
					$node->content['body'][0]['#markup'] = str_replace($string17, $banner_added17, $node->content['body'][0]['#markup']);
				}
			}
    }
  }
  // Add the ad placement at the end of the article
  // For Crime:

  if ($node->type == 'article') {
		$copyright = '<div class="copyright"> &copy; ' . date('Y') . ' Copyright Hyde Interactive, Inc. All rights reserved. This material may not be published, broadcast, rewritten, or redistributed.</div>';
    switch ($t) {
      case 'crime':
        $node->content['body'][0]['#markup'] .= $copyright . '<!-- SALive_BLW_Crime --><div id=\'div-gpt-ad-1425500431462-8\' class=\'ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-8\');</script></div>';
        break;
      case 'crashes':
        $node->content['body'][0]['#markup'] .= $copyright . '<!-- SALive_BLW_Crash --><div id=\'div-gpt-ad-1425500431462-7\' class=\'ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-7\');</script></div>';
        break;
      case 'health':
        $node->content['body'][0]['#markup'] .= $copyright . '<!-- SALive_BLW_Health --><div id=\'div-gpt-ad-1425500431462-9\' class=\'ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-9\');</script></div>';
        break;
      default:
        if ($node->nid != '6') {
          $node->content['body'][0]['#markup'] .= $copyright . '<!-- SALive_BLW_Story --><div id=\'div-gpt-ad-1425500431462-12\' class=\'ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-12\');</script></div>';
        }
        break;
    }
    $thumbs = views_embed_view('news_thumbs', 'block');
    $node->content['body'][0]['#markup'] .= '<div id="block-views-news-thumbs-block" class="clearfix"><h2>Recommended for You</h2>' . $thumbs . '</div>';  
  }
	if ($node->type == 'venue') {
	  $node->content['field_map'][0]['#markup'] .= '<!-- SALive_BLW_Venue --><div id=\'div-gpt-ad-1425500431462-13\' class=\'ads\'><script type=\'text/javascript\'>googletag.display(\'div-gpt-ad-1425500431462-13\');</script></div>';
	}
  return $node;
}

