<?php

/**
 * @file liveinterstitual.module
 * TODO: Enter file description here.
 */

 /**
  * Implements hook_init()
  */
function liveinterstitual_init() {
  // adds video popup
	drupal_add_js('//fast.wistia.com/assets/external/E-v1.js', 'external;');
	drupal_add_js(libraries_get_path('jquery-popup-overlay') . '/jquery.popupoverlay.js');
  drupal_add_js(drupal_get_path('module', 'liveinterstitual') . '/js/liveinterstitual.js');
  drupal_add_css(drupal_get_path('module', 'liveinterstitual') . '/assets/liveinterstitual.css');
}

/**
 * Implements hook_menu().
 */
function liveinterstitual_menu() {
  $items = array();
  
  $items['welcome'] = array(
    'title' => 'Welcome to San Angelo LIVE!',
    'page callback' => 'liveinterstitual_welcome_page',
    'page arguments' => array(),
    'access arguments' => array('access content'),
  );
  $items['get/ajax/wistia'] = array(
    'page callback' => 'liveinterstitual_ajax_video', // Render HTML
    'delivery callback' => 'liveinterstitual_ajax_callback', 
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Page callback to deliver the html for the video
 */
function liveinterstitual_ajax_video() {
  //First, get the block
  $block = module_invoke('liveinterstitual', 'block_view', 'interstitual');
  return render($block);
}
function liveinterstitual_ajax_callback($page_callback) {
  print $page_callback;
  drupal_page_footer();
}

function liveinterstitual_welcome_page() {
  // If you want the sidebars and everything in the theme layer, uncomment the next line
  //return theme('liveinterstitual', array('content' => $content));
  //else, to spit out a static html page, save the page to this module's dir and do this:
  echo file_get_contents( drupal_get_path('module','liveinterstitual') . '/liveinterstitiual.html');
  //Shut down Drupal cleanly
  drupal_page_footer();
}

/**
* Implements hook_block_info().
*/
function liveinterstitual_block_info() {
  $blocks = array();
  $blocks['interstitual'] = array(
    'info' => t('LIVE! Interstitual Block'),
  );
  $blocks['interstitualtag'] = array(
    'info' => t('Interstitual Tag Activation'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function liveinterstitual_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'interstitual':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => _liveinterstitual_block_content(),
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'liveinterstitual') . '/js/liveinterstitual.js',
          ),
        ),
      );
      break;
    case 'interstitualtag':
      $block['content'] = array(
        '#markup' => variable_get('liveinterstitual_video_id', 'khgd0i4fba'),
      );
    break;
  }
  return $block;
}

/**
 * custom function to generate block content
 */
function  _liveinterstitual_block_content($video_id) {
  if (!isset($video_id)) {
    $video_id = variable_get('liveinterstitual_video_id', 'khgd0i4fba');
  }
  $output = '';
  $output = <<<EOT
<div class="wistia-block-header">
  <span id="counter">Loading...</span>
</div>
<div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
  <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
    <div class="wistia_embed wistia_async_$video_id videoFoam=true" style="height:100%;width:100%">&nbsp;
    </div>
  </div>
</div>
EOT;
   return $output;
}

/**
 * Implements hook_block_configure
 */
function liveinterstitual_block_configure($delta = '') {
  $form = array();
  if ($delta == 'interstitual' || $delta == 'interstitualtag') {
    $form['video_id'] = array(
      '#type' => 'textfield',
      '#title' => t('Enter the Video ID from Wistia'),
      '#default_value' => variable_get('liveinterstitual_video_id', 'khgd0i4fba'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save()
 */
function liveinterstitual_block_save($delta, $edit) {
  if ($delta == 'interstitual') {
    variable_set('liveinterstitual_video_id', $edit['video_id']);
  }
}
/*
 * Implements hook_theme()
 *
 */

function liveinterstitual_theme($existing, $type, $theme, $path) {
  return array(
    'liveinterstitual' => array(
      'arguments' => array('content' => null),
      'variables' => array('content' => null),
      'template' => 'liveinterstitual',
      'path' => drupal_get_path('module', 'liveinterstitual'),
    )
  );
}


