<?php
/**
 * @file
 * liveadcontext.default_dfp_tags.inc
 */

/**
 * Implements hook_default_dfp_tag().
 */
function liveadcontext_default_dfp_tag() {
  $export = array();

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = '300x600_rail';
  $tag->slot = '300x600 Rail';
  $tag->adunit = '300x600Rail';
  $tag->size = '300x600,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x600',
      ),
      1 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
      2 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x600',
      ),
    ),
  );
  $export['300x600_rail'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Jobs';
  $tag->adunit = 'SALive_BLW_Jobs';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Thought';
  $tag->adunit = 'SALive_BLW_Thought';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Health';
  $tag->adunit = 'SALive_BLW_Health';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_clone_of_salive_b_rail_1';
  $tag->slot = 'SALive_B_Rail_4';
  $tag->adunit = 'SALive_B_Rail_4';
  $tag->size = '300x250,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x250',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_clone_of_salive_b_rail_1'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Business';
  $tag->adunit = 'SALive_BLW_Business';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_salive_b_rail_1';
  $tag->slot = 'SALive_B_Rail_3';
  $tag->adunit = 'SALive_B_Rail_3';
  $tag->size = '300x250,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x250',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_salive_b_rail_1'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Crash';
  $tag->adunit = 'SALive_BLW_Crash';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_salive_b_rail_1';
  $tag->slot = 'SALive_B_Rail_2';
  $tag->adunit = 'SALive_B_Rail_2';
  $tag->size = '300x250,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x250',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
    ),
  );
  $export['clone_of_clone_of_salive_b_rail_1'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Crime';
  $tag->adunit = 'SALive_BLW_Crime';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_salive_b_rail_1';
  $tag->slot = 'SALive_B_Rail_S';
  $tag->adunit = 'SALive_B_Rail_S';
  $tag->size = '300x250,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x250',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
    ),
  );
  $export['clone_of_salive_b_rail_1'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'clone_of_salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Editors_Pick';
  $tag->adunit = 'SALive_BLW_Editors_Pick';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['clone_of_salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_b_rail_1';
  $tag->slot = 'SALive_B_Rail_1';
  $tag->adunit = 'SALive_B_Rail_1';
  $tag->size = '300x250,180x150';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '300x250',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '180x150',
      ),
    ),
  );
  $export['salive_b_rail_1'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_blw_hot_rants';
  $tag->slot = 'SALive_BLW_Hot_Rants';
  $tag->adunit = 'SALive_BLW_Hot_Rants';
  $tag->size = '930x180,300x250,710x137,580x112';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '930x180',
      ),
      1 => array(
        'browser_size' => '1200x200',
        'ad_sizes' => '710x137',
      ),
      2 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '580x112',
      ),
      3 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['salive_blw_hot_rants'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_blw_most_recent_';
  $tag->slot = 'SALive_BLW_Most_Recent ';
  $tag->adunit = 'SALive_BLW_Most_Recent';
  $tag->size = '970x250,970x90,930x180,300x250';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1199x200',
        'ad_sizes' => '970x250,930x180',
      ),
      1 => array(
        'browser_size' => '992x200',
        'ad_sizes' => '930x180',
      ),
      2 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['salive_blw_most_recent_'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_bst_weather';
  $tag->slot = 'SALive_BST_Weather';
  $tag->adunit = 'SALive_BST_Weather';
  $tag->size = '190x63, 240x80, 300x100';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '1585x200',
        'ad_sizes' => '300x100',
      ),
      1 => array(
        'browser_size' => '1199x200',
        'ad_sizes' => '240x80',
      ),
      2 => array(
        'browser_size' => '991x200',
        'ad_sizes' => '300x100',
      ),
    ),
  );
  $export['salive_bst_weather'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_bw_bottom';
  $tag->slot = 'SALive_BW_Bottom';
  $tag->adunit = 'SALive_BW_Bottom';
  $tag->size = '728x90, 300x250';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => '',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '758x200',
        'ad_sizes' => '728x90',
      ),
      1 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
    ),
  );
  $export['salive_bw_bottom'] = $tag;

  $tag = new stdClass();
  $tag->disabled = FALSE; /* Edit this to true to make a default tag disabled initially */
  $tag->api_version = 1;
  $tag->machinename = 'salive_bw_top';
  $tag->slot = 'SALive_BW_Top';
  $tag->adunit = 'SALive_BW_Top';
  $tag->size = '300x250,728x90';
  $tag->block = 1;
  $tag->settings = array(
    'out_of_page' => 0,
    'slug' => '',
    'short_tag' => 0,
    'adsense_ad_types' => 'text_image',
    'adsense_channel_ids' => '',
    'adsense_colors' => array(
      'background' => '',
      'border' => '',
      'link' => '',
      'text' => '',
      'url' => '',
    ),
    'targeting' => array(),
    'breakpoints' => array(
      0 => array(
        'browser_size' => '0x0',
        'ad_sizes' => '300x250',
      ),
      1 => array(
        'browser_size' => '758x200',
        'ad_sizes' => '728x90',
      ),
    ),
  );
  $export['salive_bw_top'] = $tag;

  return $export;
}
