<?php
/**
 * @file
 * Code for the livescores feature.
 */

include_once 'livescores.features.inc';


function livescores_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'game_node_form') {
    $form['#submit'][] = 'livescore_form_submit';
    $form['title']['#access'] = FALSE;
    $form['field_home_total']['#access'] = FALSE;
    $form['field_visitors_total']['#access'] = FALSE;
  }
  $i = 0;
}
function livescore_form_submit($form, &$form_state) {
  // Change the title to someting from the node referenced
  $visitor_node = node_load($form_state['values']['field_visiting_team'][LANGUAGE_NONE][0]['target_id']);
  $home_node = node_load($form_state['values']['field_home_team'][LANGUAGE_NONE][0]['target_id']);
  $form_state['values']['title'] = $visitor_node->title . ' vs ' . $home_node->title;
  // Calculate the total
  // Home team
  $home_score = $form_state['values']['field_home_q1'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_home_q2'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_home_q3'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_home_q4'][LANGUAGE_NONE][0]['value'];
  $visitors_score = $form_state['values']['field_visit_q1'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_visit_q2'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_visit_q3'][LANGUAGE_NONE][0]['value'] +
  $form_state['values']['field_visit_q4'][LANGUAGE_NONE][0]['value'];
  $form_state['values']['field_visitors_total'][LANGUAGE_NONE][0]['value'] = $visitors_score;
  $form_state['values']['field_home_total'][LANGUAGE_NONE][0]['value'] = $home_score;
}
