<?php

/**
 * @file
 * Install / Uninstall hook for Roost.
 */

/**
 * Implements hook_install().
 */
function roost_install() {
  variable_set('roost_auto_push', FALSE);
}

/**
 * Implements hook_uninstall().
 */
function roost_uninstall() {
  variable_del('roost_key');
  variable_del('roost_secret');
  variable_del('roost_name');
  variable_del('roost_all_features');
  variable_del('roost_auto_push');
  variable_del('roost_mobile_push_support');
}
