<?php

/**
 * Implements hook_menu().
 */
function livelogin_menu() {
  $items['buy/openhouse'] = array(
    'title' => 'Purchase a Listing',
    'page callback' => 'livelogin_buy',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['buy/job'] = array(
    'title' => 'Puchase a Job Listing',
    'page callback' => 'livelogin_buy',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * page callback for menu items above
 */
function livelogin_buy($arg) {
  if (user_is_anonymous()){
    setcookie('buy', 'node/add/' . $arg, time() + 36000, '/');
    drupal_set_message('You must first log in or create an account on San Angelo LIVE!', 'status');
    drupal_goto('user');
  }
  else {
    drupal_goto('node/add/' . $arg);
  }
}

/**
 * form builder for making comment login
 */
function livelogin_comment_form($form, &$form_state) {
  $query = drupal_get_destination();
  $form = array();
  $form['#title'] = t('Sign up and comment');
  $form['#action'] = 'https://secure.sanangelolive.com/user/register?destination=' . $query['destination'];
  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#required' => TRUE,
    '#weight' => 0,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Your email address'),
    '#required' => TRUE,
    '#weight' => 1,
  );
  $form['comment'] = array(
    '#type' => 'text_format',
    '#title' => t('Your Comment'),
    '#weight' => 3,
    '#prefix' => '<p style="clear: both;">' . t('Please check your email inbox after signing up. Your comment will not post until you have confirmed your identity.') . '</p>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Comment'),
    '#weight' => 10,
  );
  return $form;
}

/**
 * Implements hook form alter
 */
function livelogin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    (isset($_POST['username']) ? $form['account']['name']['#default_value'] = $_POST['username'] : '');
    (isset($_POST['email']) ? $form['account']['mail']['#default_value'] = $_POST['email'] : '');
    if (isset($_POST['comment']['value'])) {
      // Set some cookies.
      setcookie("register_comment_words", $_POST['comment']['value'], time() + 36000, '/');
    }
    $return_path = $_REQUEST['destination'];
    setcookie("register_comment_path", $return_path, time() + 36000, '/');
  }
}

/**
 * Implements hook_page_build()
 */
function livelogin_page_alter(&$page) {
  if (isset($_COOKIE['buy'])) {
    drupal_set_message('You can continue to post your paid post @here.', array('@here' => l('here', $_COOKIE['buy'])));
  }
}
/**
 * Implements hook_user_login
 */
function livelogin_user_login(&$edit, $account) {
  if (isset($_COOKIE['register_comment_path'])) {
    $edit['redirect'] = htmlspecialchars_decode($_COOKIE['register_comment_path']);
    setcookie("register_comment_path", '', time() - 10);
  }
}

/**
 * Implements hook_node_view()
 */
function livelogin_node_view($node, $view_mode, $langcode) {
  drupal_add_js(drupal_get_path('module', 'livelogin') . '/js/livelogin.js');
}

/**
 * Implements hook_init()
 */
function livelogin_init() {
  // jquery.cookie plugin is not being loaded for anonymous users
  // causing all jQuery and Javascript to break on the site.
  drupal_add_library('system', 'jquery.cookie');
}
