<?php

/**
 * Implements hook_user_operations().
 */
 
function user_password_resets_user_operations() {
  $operations = array(
    'emailpasswordreset' => array(
      'label' => t('Email password reset link'), 
      'callback' => 'user_password_resets_user_operations_emailpasswordreset',
    )
  );
  return $operations;
}

/**
 * Callback function for admin mass emailing user password resets.
 */
 
function user_password_resets_user_operations_emailpasswordreset($accounts) {
    global $user;
    $accounts = user_load_multiple($accounts);
    foreach ($accounts as $account){
      _user_mail_notify('password_reset', $account); // Mail one time login URL and instructions using their current language.
      watchdog('user', '%user emailed password reset instructions to %name at %email.', array('%user'=>$user->name,  '%name' => $account->name, '%email' => $account->mail));
    }
}
